---
title: "Class 15: Sixteen Personality Factors I"
author: "Taylor Arnold"
output: html_notebook
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(eval = TRUE)
knitr::opts_chunk$set(fig.path = "../assets/class15-16pf/")
knitr::opts_chunk$set(fig.height = 5)
knitr::opts_chunk$set(fig.width = 8.5)
knitr::opts_chunk$set(out.width = "100%")
knitr::opts_chunk$set(dpi = 300)
```

```{r, message = FALSE, include = FALSE}
library(readr)
library(ggplot2)
library(dplyr)
library(viridis)
library(kableExtra)
library(smodels)

theme_set(theme_minimal())
msleep <- na.omit(msleep)
```

## Objectives

This week, in addition to having some time to work on Project C, we will be
working together on applying techniques from statistical inference to a data
set of responses to a personality test called *Cattell's 16 personality
factors*. Start by (quickly) taking the test yourself:

- [16 Preliminary IPIP Scales](https://openpsychometrics.org/tests/16PF.php)


See the Wikipedia page [16PF Questions](https://en.wikipedia.org/wiki/16PF_Questionnaire)
For more details.






